#90 upgrade requirements
OnroerendErfgoed/skosprovider_rdf pull request #91
Opened 2021-11-24 10:06 UTC by roefem

2021-11-24 10:33 UTC, vancamti approved these changes

2021-11-24 10:48 UTC, Wim-De-Clercq commented
Niet vergeten dat skosprovider zelf ook nog omhoog zal moeten. Dus ticket nog niet in klaar voor test zetten ofzo.

2021-12-13 07:47 UTC, Wim-De-Clercq requested changes

2021-12-13 07:47 UTC, Wim-De-Clercq commented on requirements-dev.txt
> +pytest-cov==3.0.0
Hier kan ook lijn 5 weg en 6 moet hoger. Eventueel andere versies ook, kheb niet gekeken.

2021-12-15 14:07 UTC, Wim-De-Clercq approved these changes

2021-12-17 10:13 UTC, merged